version: '2'
services:
  user_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: on-failure
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: password